#配置端口
server:
   port: 8088
   

spring:
   #配置数据源
   datasource:
      url: jdbc:mysql://127.0.0.1/zblog
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: a
   #resources:
   #   static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:/socket/imagsforblog/
   #静态资源映射配置
   #mvc:
   #  static-path-pattern: /uploads/**
               
#日志配置
logging:
   level:
      com:
         zhi:
           zblog:
               dao: debug
               web: warn
               

     



