#debug: true 可以查看哪些自动配置类生效了，哪些没有生效
#debug: true
#yml文件不能使用制表符空格tab，只能用普通空格表示缩进
#设置值 使用空格
server:
  port: 8080

#配置数据源
spring:
   datasource:
      url: jdbc:mysql://127.0.0.1/c83-s2-ply-damai
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: a
#邮件发送 Yml配置规则，如果某个节点有重复配置情况，必须要合并
   mail:
      #邮箱服务器地址
      host: smtp.qq.com
      #用户名
      username: 2438796862@qq.com
      #密码
      password: hsjsbgwoevdzebeg
      default-encoding: UTF-8
   #profiles: 
      #指定使用哪一个环境，当前指定为成测试环境
      #active: test
#日志配置
logging:
   level:
      com:
         yc:
            springboot:
               dao: debug
               web: warn
   
#以谁来发送右键==》用户自定义的属性
mail:
   fromMail:
      addr: 2438796862@qq.com
      
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名
    
   
   
#yml文件可以通过---来分割文件    
---
#测试环境  
server:
  port: 8081
spring: 
  #该环境的名称
  profiles: test
  
---
server:
  port: 8082
spring: 
  #该环境的名称
  profiles: dev
  
  
      